### ISSUE TITLE
python library does not work on platforms different than Linux

### ISSUE THREAD

**Issue by agosiewska** [WojciechKretowicz/vimo#2]
Variable 'info' is created only for Linux platform

https://github.com/WojciechKretowicz/weles/blob/1cd7bda740ddfdde56b9ee4748145795d84194f0/python/weles/models.py#L78-L86

**Comment by agosiewska** [comment]
How about adding AppVeyor integration?
https://www.appveyor.com/

**Comment by WojciechKretowicz** [comment]
solved
